export const ADD_NEW_COMPANY = "ADD_NEW_COMPANY";
export const ADD_NEW_PERSON = "ADD_NEW_PERSON";
export const TOGGLE_CLICK = "TOGGLE_CLICK";
export const SET_COMPANY_ERROR = "SET_COMPANY_ERROR";
export const SET_PERSON_ERROR = "SET_PERSON_ERROR";
export const SELECT_COMPANY = "SELECT_COMPANY";
export const FETCH_COMPANIES = "FETCH_COMPANIES";
export const FETCH_PERSONS = "FETCH_PERSONS";
